### ISSUE TITLE
Add capability to manage links

### ISSUE THREAD

**Issue by lindgren** [ExpediaGroup/flyte-jira#14]
Add capability to be able to 
* Link issues
* Get issue link
* Delete issue link

API reference: https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issueLink

**Comment by mateiidavid** [comment]
[api-ref]: https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issueLink
@lindgren there is a slight issue with implementing this using the [API reference][api-ref]:
 
1. To get an issue link, we would have to know the `id` of the link. My suggestion is to do some pattern matching on the argument here:
 - if we do a `link_get()` with an input that fits a jira ticketId, we return all of the links for that issue as an array
 - if we do a `link_get()` with a linkId, we return the actual link.

For example:
input A
```json
{
  "id": "JIRA-123"
}
```
would give us an array with all of the linkIds `links: [1001, 1002, ...]`

```json
{
  "id": "1001",
}
```
would give us the actual link, as documented by the [API ref][api-ref].

OR

2. Whenever a `link_get()` or  `remove_link()` is called, if the input is invald (i.e is of form JIRA-123) we return in the error message all of the possible links for the ticket specified. The downside to this is that once we return the links/

e.g for the input
```json
{
  "id": "JIRA-123"
}
```

we return an error message:
```
err = Link ID not supported, please use a supported linkId
linkIds = [1001, 1002, 1003]
print(err)
for link in linkIds 
   display link
```
