### ISSUE TITLE
Add capability to manage transitions

### ISSUE THREAD

**Issue by lindgren** [ExpediaGroup/flyte-jira#15]
Add capabilities to
* Do transition
* Get transition

API ref: https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-doTransition

**Comment by YToutah993** [comment]
PRs:

- **Get Transitions:** https://github.com/ExpediaGroup/flyte-jira/pull/25
- **Do Transition:** https://github.com/ExpediaGroup/flyte-jira/pull/23
